
class Config {
   constructor() {

   }
}

Config.headers = {
    // Authorization: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNzciLCJjcmVhdGVkIjoxNTQzODg3NTk2NTk1LCJzY29wZSI6bnVsbCwiaXNzIjoiY3VzdG9tZXJfc3R1ZGVudF9hcHAiLCJleHAiOjE1NDY0Nzk1OTYsIm5vbmNlU3RyIjoiZTlscG84aWZiNzl0ZTdhZiJ9.c0i-plKYDTBCsiKAzGIJq08m9IkJG2t-UPGzQqPF5Cp3g3YSsvejeEBSsLR1W02JGNOIbxjfpYxKYe6N_7omLw"
    // Authorization: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMjgiLCJjcmVhdGVkIjoxNTQ1MjE0MTgzMTczLCJzY29wZSI6bnVsbCwiaXNzIjoiY3VzdG9tZXJfc3R1ZGVudF9hcHAiLCJleHAiOjE1NDc4MDYxODMsIm5vbmNlU3RyIjoidWtxcjkxMTR2bGIyOHFqOSJ9.9jsWg9j0riD0coYVsYTvej18TCEAr2Wp_mgheOUqefsD02_VCviaFvk-0DGSprZYvlkinA28AJZFXAxYbwyMYA"
     Authorization: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMjciLCJjcmVhdGVkIjoxNTQ1MTg2MDI4NzI4LCJzY29wZSI6bnVsbCwiaXNzIjoiY3VzdG9tZXJfc3R1ZGVudF9hcHAiLCJleHAiOjE1NDc3NzgwMjgsIm5vbmNlU3RyIjoiMGtncmtraG5oczJxbGJoaSJ9.CJmJItajfc7NAsFTP6MhbzTBLx9XXT1hunGLi3KfkDmXZB4BhQbCYedapHYYp9Bph5_CjGqT8NrDbH2iZOtUAg"
  };

export { Config };
